"""
Django settings for crowdclick project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from collections import namedtuple
from datetime import timedelta

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '39h^zm85$8ehrv+_1o=d-k9caiu_e=$)0oti42w9)krz4@6_0c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

TEST = ('test' in sys.argv) or ('unittest' in sys.argv)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'django_celery_beat',
    'django_celery_results',
    'django_filters',
    'drf_yasg',

    'ad_source',
]

MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crowdclick.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            'ad_source'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crowdclick.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'web3auth.backend.Web3Backend'
]

DJANGO_ADMIN_URL = 'admin'

# Rest Framework https://www.django-rest-framework.org/
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication'
    ),
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
}

ACCOUNT_OWNER_PUBLIC_KEY = '0x9c76e3A23A87f624aAdEff7ca5e74103476eD11C'  # ServerConfigViewSet

# Web3
AUTH_NONCE_CHOICES = '0123456789abcdef'
AUTH_NONCE_LENGTH = 32
LOGIN_REDIRECT_URL = '/'

web3_config_namedtuple = namedtuple('Web3_Config', [
    'endpoint', 'contract_address', 'chain_id', 'public_key', 'private_key', 'default_gas_fee'
])
WEB3_CONFIG = {
    'mumbai': web3_config_namedtuple(
        endpoint='https://rpc-mumbai.matic.today',
        contract_address='0xb312aC99b9207286addf566B5BB08f7552aF0b15',
        chain_id=80001,
        public_key=ACCOUNT_OWNER_PUBLIC_KEY,
        private_key='a' * 64,
        default_gas_fee=100000,
    ),
    'goerli': web3_config_namedtuple(
        endpoint='https://goerli.infura.io/v3/' + 'a' * 32,
        contract_address='0x5f9A718D919463443A74A67Deb1aF056790C0ca0',
        chain_id=5,
        public_key=ACCOUNT_OWNER_PUBLIC_KEY,
        private_key='a' * 64,
        default_gas_fee=2000000,
    ),
    'bsc_testnet': web3_config_namedtuple(
        endpoint='https://data-seed-prebsc-1-s1.binance.org:8545',
        contract_address='',
        chain_id=97,
        public_key=ACCOUNT_OWNER_PUBLIC_KEY,
        private_key='a' * 64,
        default_gas_fee=2000000,
    )
}

# Task queue
BROKER_URL = 'pyamqp://guest@localhost//'

# Celery
CELERY_RESULT_BACKEND = 'django-db'

# CELERY_RESULT_BACKEND = 'django-cache'

CELERY_BEAT_SCHEDULE = {
    'update-task-is-active-balance': {
        'task': 'ad_source.tasks.update_task_is_active_balance',
        'schedule': timedelta(minutes=1),
        'options': {
            'expires': 60
        }
    },
}

ACCOUNT_OWNER_PUBLIC_KEY = '0xDd2179e8D8755f810CdAe4a474F7c53F371FbB6A'  # ServerConfigViewSet

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, '../db.sqlite3'),
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

if 'test' in sys.argv:
    CACHES['default'] = {'BACKEND': 'django.core.cache.backends.dummy.DummyCache'}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

MEDIA_ROOT = 'assets/'
LOGOUT_REDIRECT_URL = '/'

STATIC_URL = '/backend_static/'
STATIC_ROOT = 'static'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
