# Generated by Django 2.2.5 on 2019-10-26 14:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_link', models.URLField(verbose_name='Website Link')),
                ('title', models.CharField(max_length=35, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('reward_per_click', models.FloatField(default=1, verbose_name='Reward per click')),
                ('time_duration', models.DurationField(default=datetime.timedelta(0, 30), verbose_name='Time duration')),
            ],
            options={
                'ordering': ['-reward_per_click'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('question_type', models.CharField(choices=[('RA', 'Radio'), ('SE', 'Select')], max_length=2)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ad_source.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ad_source.Question')),
            ],
        ),
    ]
