# Generated by Django 2.2.5 on 2019-09-28 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='time_duration',
            field=models.DurationField(default=datetime.timedelta(7), verbose_name='Time duration'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ad_source.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ad_source.Advertisement'),
        ),
    ]
