# Generated by Django 2.2.5 on 2019-09-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0002_default_duration_one_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='reward_per_click',
            field=models.FloatField(default=1, verbose_name='Reward per click'),
        ),
    ]
