# Generated by Django 2.2.7 on 2019-12-01 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0003_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('result_count', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='placeholder.png', upload_to='task_image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='task',
            name='spend_daily',
            field=models.DecimalField(decimal_places=3, default=20, max_digits=9, verbose_name='Max budget to spend per day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('RA', 'Radio'), ('SE', 'Select')], default='SE', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward_per_click',
            field=models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Reward per click'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ad_source.Question'),
        ),
    ]
