# Generated by Django 2.2.8 on 2019-12-20 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0004_auto_20191201_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default='placeholder.png', upload_to='assets/task_image', verbose_name='Image'),
        ),
    ]
