# Generated by Django 2.2.8 on 2020-01-09 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad_source', '0006_answer_answeredquestion_selectedoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='result_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='result_count',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
