# Generated by Django 2.2.9 on 2020-02-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0008_task_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.AddField(
            model_name='task',
            name='og_image_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='OpenGraph Image Path'),
        ),
    ]
