# Generated by Django 2.2.10 on 2020-02-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0009_task_open_graph_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='og_image_link',
            field=models.URLField(blank=True, null=True, verbose_name='OpenGraph Image Path'),
        ),
    ]
