# Generated by Django 2.2.10 on 2020-03-08 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0011_task_is_active_true_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='website_link',
            field=models.CharField(max_length=200, validators=[django.core.validators.URLValidator], verbose_name='Website Link'),
        ),
    ]
