# Generated by Django 2.2.13 on 2020-06-26 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward_migrate_answers_to_temp_answers(apps, schema_editor):
    AnsweredQuestion = apps.get_model("ad_source", "AnsweredQuestion")
    TempAnswer = apps.get_model("ad_source", "TempAnswer")

    qs = AnsweredQuestion.objects.all().values_list(
        'question__task', 'selected_option__option', 'answers__user', 'answers__timestamp')
    for (task, option, user, timestamp) in qs:
        temp_answer = TempAnswer.objects.create(
            user_id=user,
            task_id=task,
            timestamp=timestamp,
        )
        temp_answer.selected_options.add(option)


def reverse_migrate_answers_to_temp_answers(apps, schema_editor):
    TempAnswer = apps.get_model("ad_source", "TempAnswer")
    TempAnswer.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ad_source', '0012_website_link_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeredquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to='ad_source.Question'),
        ),
        migrations.CreateModel(
            name='TempAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('selected_options', models.ManyToManyField(related_name='temp_answers', to='ad_source.Option')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temp_answers', to='ad_source.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temp_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            forward_migrate_answers_to_temp_answers,
            reverse_migrate_answers_to_temp_answers
        )
    ]
