# Generated by Django 2.2.13 on 2020-10-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0016_init_reward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-reward_per_click'], 'verbose_name_plural': 'Task'},
        ),
        migrations.AddField(
            model_name='task',
            name='chain',
            field=models.CharField(choices=[('goerli', 'Goerli'), ('mumbai', 'Mumbai')], default='goerli', max_length=15),
        ),
    ]
