# Generated by Django 2.2.13 on 2020-11-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0017_task_chain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Task'},
        ),
        migrations.AddField(
            model_name='task',
            name='contract_address',
            field=models.CharField(default='', max_length=42, verbose_name='Contract address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AddField(
            model_name='task',
            name='warning_message',
            field=models.CharField(blank=True, max_length=100, verbose_name='Warning message'),
        ),
        migrations.AlterField(
            model_name='task',
            name='chain',
            field=models.CharField(choices=[('goerli', 'Goerli'), ('mumbai', 'Mumbai')], default='goerli', max_length=15, verbose_name='Chain'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
