# Generated by Django 2.2.13 on 2021-03-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0018_task_contract_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='chain',
            field=models.CharField(choices=[('goerli', 'Goerli'), ('mumbai', 'Mumbai'), ('bsc_testnet', 'bsc_testnet')], default='goerli', max_length=15, verbose_name='Chain'),
        ),
    ]
