# Generated by Django 2.2.18 on 2021-03-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0020_add_binance_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active_web3',
            field=models.BooleanField(default=True, verbose_name='Is active on Web3'),
        ),
        migrations.AddField(
            model_name='task',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9, verbose_name='Remaining balance for task'),
            preserve_default=False,
        ),
    ]
