# Generated by Django 2.2.20 on 2021-04-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0021_task_web3_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='uuid',
            field=models.CharField(max_length=36, null=True, unique=True, verbose_name='Web3 Task Identifier'),
        ),
    ]
