# Generated by Django 2.2.18 on 2021-04-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0021_task_web3_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='website_image',
            field=models.ImageField(null=True, upload_to='task_website_image', verbose_name='Website Image'),
        ),
    ]
