# Generated by Django 2.2.20 on 2021-04-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0024_task_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='initial_budget',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=9, null=True, verbose_name='Initial task budget '),
        ),
    ]
