# Generated by Django 2.2.20 on 2021-05-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0025_task_initial_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='initial_tx_hash',
            field=models.CharField(blank=True, default='', max_length=66, verbose_name='Initial transaction hash'),
        ),
    ]
