# Generated by Django 3.2.2 on 2021-06-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0026_task_initial_tx_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(),
        ),
    ]
