# Generated by Django 3.2.2 on 2021-06-27 12:35

import ad_source.fields
from django.db import migrations, models
import djmoney.models.fields


def delete_tasks(apps, schema_editor):
    Reward = apps.get_model('ad_source', 'Reward')
    Answer = apps.get_model('ad_source', 'Answer')
    Task = apps.get_model('ad_source', 'Task')
    Reward.objects.all().delete()
    Answer.objects.all().delete()
    Task.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0027_task_option_title__textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='chain',
            field=models.CharField(
                choices=[('goerli', 'Goerli (ETH)'), ('mumbai', 'Mumbai (MATIC)'), ('bsc_testnet', 'bsc_testnet (BNB)'), ('bsc_mainnet', 'bsc_mainnet (BNB)')], default='goerli', max_length=15, verbose_name='Chain'),
        ),
        migrations.AddField(
            model_name='task',
            name='currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('BNB', 'BNB'), ('ETH', 'ETH'), ('MATIC', 'MATIC'), ('USD', 'USD')], default='USD',
                editable=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='initial_budget',
            field=ad_source.fields.MoneyField(currency_field_name='currency', decimal_places=10, default=None, max_digits=18, null=True, verbose_name='Initial task budget'),
        ),
        migrations.AlterField(
            model_name='task',
            name='remaining_balance',
            field=ad_source.fields.MoneyField(currency_field_name='currency', decimal_places=10, default=None, max_digits=18, null=True, verbose_name='Remaining balance for task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward_per_click',
            field=ad_source.fields.MoneyField(currency_field_name='currency', decimal_places=10, max_digits=18, verbose_name='Reward per click'),
        ),
        migrations.RunPython(delete_tasks, reverse_code=migrations.RunPython.noop),
    ]
