# Generated by Django 3.2.2 on 2021-08-07 11:14

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0028_reward_per_click_moneyfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='chain',
            field=models.CharField(choices=[('goerli', 'Goerli (ETH)'), ('mumbai', 'Mumbai (MATIC)'), ('polygon', 'Polygon (Matic)'), ('bsc_testnet', 'bsc_testnet (BNB)'), ('bsc_mainnet', 'bsc_mainnet (BNB)')], default='goerli', max_length=15, verbose_name='Chain'),
        ),
        migrations.AlterField(
            model_name='task',
            name='currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BNB', 'BNB'), ('ETH', 'ETH'), ('MATIC', 'MATIC'), ('USD', 'USD')], default=None, editable=False, max_length=5, null=True),
        ),
    ]
