# Generated by Django 3.2.6 on 2021-09-26 10:39

from django.db import migrations, models

import ad_source.models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_source', '0030_task_sku_and_private'),
    ]

    operations = [
            migrations.AlterField(
            model_name='task',
            name='sku',
            field=models.CharField(blank=True, default=ad_source.models.generate_task_sku, max_length=6, unique=True, verbose_name='SKU'),
        ),
    ]
