# Group Tasks

## Task Collection [/api/task/]

### List All Tasks [GET]

+ Response 200 (application/json)

        {
          "count": 1,
          "next": null,
          "previous": null,
          "results": [
            {
              "id": 1,
              "title": "Check our site",
              "description": "Awesome site. Go check",
              "user": {
                "pk": 1,
                "username": "admin",
                "email": "",
                "first_name": "",
                "last_name": ""
              },
              "image": "http://localhost:8000/api/task/placeholder.png",
              "image_thumbnail": "http://localhost:8000/api/task/CACHE/images/placeholder/0ffb6f88d8f4ccf0431db0468e2b96b0.jpg",
              "website_link": "http://example.com",
              "reward_per_click": "1.000",
              "reward_usd_per_click": null,
              "spend_daily": "50.000",
              "time_duration": "00:00:30",
              "questions": [
                {
                  "id": 1,
                  "title": "Was it good?",
                  "url": "http://localhost:8000/api/question/1/",
                  "options": [
                    {
                      "id": 1,
                      "title": "Good",
                      "url": "http://localhost:8000/api/option/1/"
                    },
                    {
                      "id": 2,
                      "title": "Bad",
                      "url": "http://localhost:8000/api/option/2/"
                    }
                  ]
                },
                {
                  "id": 2,
                  "title": "Was it fast?",
                  "url": "http://localhost:8000/api/question/2/",
                  "options": [
                    {
                      "id": 3,
                      "title": "Fast",
                      "url": "http://localhost:8000/api/option/3/"
                    },
                    {
                      "id": 4,
                      "title": "Slow",
                      "url": "http://localhost:8000/api/option/4/"
                    }
                  ]
                }
              ]
            }
          ]
        }


### Create a new task [POST]

+ Request (application/json)

        {
            "title": "Check our site",
            "description": "Awesome site. Go check it now and earn crypto",
            "website_link": "http://example.com",
            "reward_per_click": 0.001,
            "time_duration": "00:00:30",
            "spend_daily": 1,
            "questions": [
                {
                    "title": "Was it good?",
                    "options": [
                        {
                            "title": "Good"
                        },
                        {
                            "title": "Bad"
                        }
                    ]
                }
            ]
        }

+ Response 201 (application/json)

    + Body

            {
                "id": 2,
                "title": "Check our site",
                "description": "Awesome site. Go check it now and earn crypto",
                "user": {
                    "pk": 1,
                    "username": "admin",
                    "email": "",
                    "first_name": "",
                    "last_name": ""
                },
                "image": "http://localhost:8000/api/task/placeholder.png",
                "image_thumbnail": "http://localhost:8000/api/task/CACHE/images/placeholder/0ffb6f88d8f4ccf0431db0468e2b96b0.jpg",
                "website_link": "http://example.com",
                "reward_per_click": "0.001",
                "reward_usd_per_click": null,
                "spend_daily": "1.000",
                "time_duration": "00:00:30",
                "questions": [
                    {
                        "id": 3,
                        "title": "Was it good?",
                        "url": "http://localhost:8000/api/question/3/",
                        "options": [
                            {
                                "id": 5,
                                "title": "Good",
                                "url": "http://localhost:8000/api/option/5/"
                            },
                            {
                                "id": 6,
                                "title": "Bad",
                                "url": "http://localhost:8000/api/option/6/"
                            }
                        ]
                    }
                ]
            }

# Group Answers

## Answer Collection [/api/task/{id}/answer]

### Create answer for task [POST]

+ Request (application/json)

        {
            "questions": [
                {
                    "id": 1,
                    "options": [
                        {
                            "id": 1
                        }
                    ]
                },
                {
                    "id": 2,
                    "options": [
                        {
                            "id": 3
                        }
                    ]
                }
            ]
        }

+ Response 200 (application/json)

        {
            "task": {
                "id": 1,
                "title": "Check our site",
                "description": "Awesome site. Go check",
                "user": {
                    "pk": 1,
                    "username": "admin",
                    "email": "",
                    "first_name": "",
                    "last_name": ""
                },
                "image": "http://localhost:8000/api/task/1/answer/placeholder.png",
                "image_thumbnail": "http://localhost:8000/api/task/1/answer/CACHE/images/placeholder/0ffb6f88d8f4ccf0431db0468e2b96b0.jpg",
                "website_link": "http://example.com",
                "reward_per_click": "1.000",
                "reward_usd_per_click": null,
                "spend_daily": "50.000",
                "time_duration": "00:00:30",
                "questions": [
                    {
                        "id": 1,
                        "title": "Was it good?",
                        "url": "http://localhost:8000/api/question/1/",
                        "options": [
                            {
                                "id": 1,
                                "title": "Good",
                                "url": "http://localhost:8000/api/option/1/"
                            },
                            {
                                "id": 2,
                                "title": "Bad",
                                "url": "http://localhost:8000/api/option/2/"
                            }
                        ]
                    },
                    {
                        "id": 2,
                        "title": "Was it fast?",
                        "url": "http://localhost:8000/api/question/2/",
                        "options": [
                            {
                                "id": 3,
                                "title": "Fast",
                                "url": "http://localhost:8000/api/option/3/"
                            },
                            {
                                "id": 4,
                                "title": "Slow",
                                "url": "http://localhost:8000/api/option/4/"
                            }
                        ]
                    }
                ]
            },
            "user": {
                "pk": 1,
                "username": "admin",
                "email": "",
                "first_name": "",
                "last_name": ""
            },
            "timestamp": "2020-01-12T12:15:30.616093Z",
            "questions": [
                {
                    "id": 14,
                    "options": [
                        {
                            "id": 15
                        }
                    ]
                },
                {
                    "id": 15,
                    "options": [
                        {
                            "id": 16
                        }
                    ]
                }
            ]
        }
